apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tldr-bot
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/Accurate0/tldr-bot.git
    path: kubernetes
    kustomize:
      images:
        - tldr-bot=ghcr.io/accurate0/tldr-bot:${ARGOCD_APP_REVISION}
  destination:
    server: https://kubernetes.default.svc
    namespace: tldr-bot
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
