services:
  tldr-bot:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=tldr-bot
    ports:
      - "8000:8000"
    links:
      - "db:database"
      - "ollama:ollama"
    depends_on:
      - db
      - ollama
    environment:
      - DATABASE_URL=postgres://postgres:test@database/bot
      - DISCORD_TOKEN
      - OLLAMA_API_BASE=http://ollama
      - OPENAI_API_KEY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 1s

  ollama:
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 60s
      retries: 5
      start_period: 90s
      timeout: 3s

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 90s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  ollama-data:
