apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: tldr-bot-secret
  namespace: tldr-bot
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: tl-dr-bot-o-xt-r
        envSlug: prod
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: tldr-bot-managed-secrets
      secretNamespace: tldr-bot
      creationPolicy: "Owner"
