name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: .
      image-name: tldr-bot
      docker-build-args: |
        BINARY_NAME=tldr-bot
      use-rust-caching: true

  deploy:
    needs:
      - build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@main
    with:
      service-name: tldr-bot
      images: ghcr.io/accurate0/tldr-bot
      manifests-path: projects/tldr-bot/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
